# Generated by Django 4.2.16 on 2024-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recomended',
            field=models.BooleanField(default=True),
        ),
    ]
